version: 2
jobs:
  build:
    working_directory: /sls-py-req
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      # Apt deps
      - run: apt -y update && apt -y install python3-pip python3.6 curl unzip
      # install nodejs
      - run: curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt -y install nodejs
      # install serverless
      - run: npm install -g serverless
      # install test deps (this plugin)
      - run: cd example && npm i ..
      # try to package!
      - run: cd example && sls package
      # unzip it and check for requests
      - run: unzip example/.serverless/sls-py-req-test.zip -d puck && ls puck/requests
      # clean before running as user
      - run: rm -r puck && cd example && SLS_DEBUG=t sls requirements clean
      # create a user
      - run: useradd -m tester
      # give this dir to the test user
      - run: chown -R tester .
      # try to package!
      - run: cd example && su -c "env SLS_DEBUG=t sls package" tester
      # unzip it and check for requests
      - run: unzip example/.serverless/sls-py-req-test.zip -d puck && ls puck/requests
