name: 🎉 Feature request
description: Suggest an idea
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists
      options:
        - label: I have searched existing issues, it hasn't been reported yet
          required: true
  - type: textarea
    attributes:
      label: Use case description
      description: Describe the use case that needs to be addressed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution (optional)
      description: |
        e.g. propose how the configuration and implementation of the new feature could look
